name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_SECRET }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy hello-cd \
          --runtime python312 \
          --trigger-http \
          --allow-unauthenticated \
          --region asia-northeast1 \
          --entry-point main
          --service-account ${{ secrets.GCP_FUNCTION_SA }} 
